version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopper-db
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - db
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - 80:80
